# Generated by Django 5.2.7 on 2025-10-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_en',
            field=models.ManyToManyField(null=True, to='movie_app.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_ru',
            field=models.ManyToManyField(null=True, to='movie_app.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_en',
            field=models.ManyToManyField(null=True, to='movie_app.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_ru',
            field=models.ManyToManyField(null=True, to='movie_app.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director_en',
            field=models.ManyToManyField(null=True, to='movie_app.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director_ru',
            field=models.ManyToManyField(null=True, to='movie_app.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_en',
            field=models.ManyToManyField(null=True, to='movie_app.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_ru',
            field=models.ManyToManyField(null=True, to='movie_app.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='language_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='language_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='parent_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='parent_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
