# Generated by Django 5.2.7 on 2025-11-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_actor_actor_name_en_actor_actor_name_ru_actor_bio_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor_ru',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country_ru',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_ru',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre_ru',
        ),
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=models.CharField(choices=[('144p', '144p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='360p'),
        ),
    ]
